### ISSUE TITLE
Bug: Bartender4 and skinning the bag bar with Hex

### ISSUE THREAD

**Issue by nancikennedy** [amtoft-eu/masque-hex#1]
When using Bartender4 and Hex as the skin for the bag bar, the art for the backpack bag is missing whether B4 is set to "One Bag" or not. This affects only the backpack and not the extra bags.

**Comment by StormFX** [comment]
I'm assuming this is in **Retail**, correct?

**Comment by StormFX** [comment]
I submitted a fix for this as seen above.
