### ISSUE TITLE
DBM installation messes with action glow

### ISSUE THREAD

**Issue by LukasDahl** [amtoft-eu/masque-hex#5]
Multiple users reports issues with square action glow while DBM is installed.

![image](https://github.com/user-attachments/assets/66b228b9-d7a6-4141-9ef5-b7a9bb721d8d)

**Comment by LukasDahl** [comment]
It might not be solvable in this project. I would have to do some testing. 

@StormFX do you have any immediate ideas as to where this issue is located? In the skin, in DBM or in Masque itself?

**Comment by StormFX** [comment]
I'm going to need more info. I search through DMB's folders and it doesn't even support Masque.

Edit: So is DBM resetting the action button glows to square or is it not utilizing the hex glow for its own buttons?
Edit2: It looks like LibButtonGlow isn't creating a `SpellActivationOverlay` field when creating modern spell alerts, so Masque skips it. LBG probably needs to be updated.

**Comment by LukasDahl** [comment]
Fixed in the latest version of DBM https://github.com/DeadlyBossMods/DeadlyBossMods/issues/1340
